# Generated by Django 4.2.16 on 2026-10-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='banners/')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('link_url', models.URLField(blank=True, help_text='Target URL when clicked')),
                ('placement', models.CharField(choices=[('hero', 'Homepage Hero'), ('sidebar', 'Sidebar'), ('category', 'Category Pages'), ('popup', 'Popup')], default='hero', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('active_from', models.DateTimeField(blank=True, null=True)),
                ('active_to', models.DateTimeField(blank=True, null=True)),
                ('track_clicks', models.BooleanField(default=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('impression_count', models.PositiveIntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'banners',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['placement', 'is_active'], name='banners_placeme_c011a9_idx')],
            },
        ),
    ]
